### ISSUE TITLE
issue of image show

### ISSUE THREAD

**Issue by lbing9002** [cocoakekeyu/markdown-img-paste#15]
i want to paste an image to .md file use markdown-img-paste plugin, but it cant show properly.
there is no problem of saving image using markdown-img-paste.
when saved as html, the html shows properly.
does anyone encountered this problem, how to fix it?
thx : )

win10
atom:1.12
markdown-preview:0.159.15

load it in .md file:
![image](https://user-images.githubusercontent.com/18423208/32132744-e70080ce-bbfb-11e7-9673-aee8ff21e69b.png)

it shows like this:
![image](https://user-images.githubusercontent.com/18423208/32132755-fb52b506-bbfb-11e7-8690-d33a0783f477.png)

**Comment by clock-z** [comment]
How to solve this problem? I have the same question.
