### ISSUE TITLE
照片路径无法在Jekyll页面上显示

### ISSUE THREAD

**Issue by Marina-Ma** [cocoakekeyu/markdown-img-paste#16]
你好：

有个小问题，照片的路径无法在Jekyll页面上显示，但是能在GitHub上显示，怎么解决呢？

我只能修改成全路径```![](https://github.com/Marina-Ma/Marina-Ma.github.io/blob/master/_posts/assets/markdown-img-paste-20171102162214894.png?raw=true)```，才能在Jekyll上显示。

是不是因为复制的图片默认在_post/assets下，导致有两个assets的关系？比如下面这篇文章的图片在两个页面中的显示：

Github
https://github.com/Marina-Ma/Marina-Ma.github.io/blob/master/_posts/2012-10-8-The-truth-of-eat.md

Blog
https://marina-ma.github.io/The-truth-of-eat/

**Comment by cocoakekeyu** [comment]
现在粘贴的图片默认在当前文件同目录下的assets文件夹， 在你的项目编写markdown应该是在_post/assets下，生成的标记是![](assets/markdown-img-paste-xxx.png)，是相对路径的，所以在编辑器和github源码编辑器都能正常看到的。

经过jekyll转换后， 标记![](assets/markdown-img-paste-xxx.png)是转成了img标签，大概如此：<img src="assets/markdown-img-paste-xxx.png" /img>， 因为是相对路径，浏览器请求就是你的域名+assets/markdown-img-paste-xxx.png，会去你的项目下assets文件找markdown-img-paste-xxx.png，找不到啦。你打开网页同时打开F12可以看到错误信息

暂时不做自定义的图片目录功能， 你可以：
1. copy 一份_post/assets下的图片到 assets/下

**Comment by cocoakekeyu** [comment]
哈，其实不行。 

如果用来编写静态博客的还是建议用七牛云存图片了， 免费、速度又快。

**Comment by Marina-Ma** [comment]
是的，本来用markdone就是想快一点，但是如果要拷贝全路径，就太麻烦了。
我先试试七牛，谢谢！

**Comment by Marina-Ma** [comment]
setting里设置好了七牛，粘贴的时候atom提示“bad token”，无法粘贴，是什么原因恩
