### ISSUE TITLE
粘贴照片时，如何修改自动保存到电脑本地文件夹的路径

### ISSUE THREAD

**Issue by clock-z** [cocoakekeyu/markdown-img-paste#20]
复制粘贴照片时，atom自动默认保存到电脑本地文件夹为桌面-image-2018-X（月），想问问如何修改自动保存路径，让照片自动保存到本人指定的文件夹里？
（新手上路，多多指教）

**Comment by cocoakekeyu** [comment]
目前暂不支持设置图片保存路径，可能以后会加上

**Comment by clock-z** [comment]
之前是默认保存到电脑本地文件夹为桌面-image-2018-X（月），后来某次胡乱操作发现可以更改图片保存路径比如某盘某文件夹-image-2018-X（月），再想复现就不得门路。。。
猜测是可以更改，只不过这个设置方法很隐蔽。。

**Comment by cocoakekeyu** [comment]
但， 我设计是保存在当前文件路径下的asset文件夹。 

在markdown文件没保存之前粘贴图片可能出现一些意料之外的BUG

**Comment by clock-z** [comment]
sokka
谢谢解释，看来是BUG，期待你未来能加上这个功能，超级实用~♥

**Comment by clock-z** [comment]
不好意思提问对象搞错了，剪贴板里的图片复制到md文件，同时自动存在桌面-image-2018-X（月）文件夹内，我所使用的快捷键是shift+cmd+i，而非是作者所建议的shift+ctrl+v。所以要问能否更改保存图片地址需要去问别的插件作者。
