### ISSUE TITLE
在 mac pro 中使用粘贴生成的图片是实际图片的2倍大，怎么解决？

### ISSUE THREAD

**Issue by zq99299** [cocoakekeyu/markdown-img-paste#34]
在 mac pro 中使用粘贴生成的图片是实际图片的2倍大，怎么解决？

用各种截图软件直接保存，截图是 500 * 500，没有问题，但是用该工具粘贴到 atom 中，
生成的图片就变成 1000 * 1000 了

**Comment by zq99299** [comment]
大佬，求修复呀，这个插件可好用了，就是我从 windows 上转到 mac pro 上的时候，发现了这个问题，
好揪心

**Comment by fatpo** [comment]
mac 感觉好模糊啊。。

**Comment by zq99299** [comment]
不是模糊，就是 2 倍大小。这个有点难受，每次需要自己转
