### ISSUE TITLE
可不可以增加批量上传功能？

### ISSUE THREAD

**Issue by wghglory** [cocoakekeyu/markdown-img-paste#8]
现在只能复制、粘贴并上传一张图片。我想很多人有时会复制一篇文章，其中有多张图片。能否正常粘贴被复制文章的文字，并自动上传文章中的多个图片呢？Mac版有个MWeb有这个功能。用户可以选择默认是把这多个图片保存到本地项目默认media/assets文件夹中，也可以自动保存到七牛，还可以先保存到本地，然后后期给予上穿到七牛的选项。

**Comment by cocoakekeyu** [comment]
此插件专注实现快速插入图片到markdown的功能。如选择图片或者批量上传七牛云功能可以找其他专用的软件哦
