### ISSUE TITLE
请问不能粘贴图片文件吗？

### ISSUE THREAD

**Issue by aqxa** [cocoakekeyu/markdown-img-paste#9]
我使用的是 Windows 系统，在资源管理器中复制一个图片文件，然后按 CTRL + SHIFT + V 粘贴，没有任何效果，使用截图以及复制网页上的图片然后粘贴没问题。

**Comment by cocoakekeyu** [comment]
插件粘贴的是复制到系统剪切板数据（包括图片），不是文件管理器中的文件。

**Comment by aqxa** [comment]
@cocoakekeyu 好的。谢谢
